// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZbSoD4_j7-hRo0v0IY3sQ-OTh9A9dcU',
    appId: '1:355231076214:web:4d53aefe30a02e5b86f457',
    messagingSenderId: '355231076214',
    projectId: 'oragnizamais',
    authDomain: 'oragnizamais.firebaseapp.com',
    storageBucket: 'oragnizamais.firebasestorage.app',
    measurementId: 'G-H0T1MX0Z0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqxzgyT9-Fd8FeLjjYZb8fy-H24jpCR90',
    appId: '1:355231076214:android:e645e603fc88d0b586f457',
    messagingSenderId: '355231076214',
    projectId: 'oragnizamais',
    storageBucket: 'oragnizamais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgebDXvFSMyzS21IVv1HTpTXH97ajHMtg',
    appId: '1:355231076214:ios:585abf46dd89ae3d86f457',
    messagingSenderId: '355231076214',
    projectId: 'oragnizamais',
    storageBucket: 'oragnizamais.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgebDXvFSMyzS21IVv1HTpTXH97ajHMtg',
    appId: '1:355231076214:ios:585abf46dd89ae3d86f457',
    messagingSenderId: '355231076214',
    projectId: 'oragnizamais',
    storageBucket: 'oragnizamais.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZbSoD4_j7-hRo0v0IY3sQ-OTh9A9dcU',
    appId: '1:355231076214:web:f242686492d914be86f457',
    messagingSenderId: '355231076214',
    projectId: 'oragnizamais',
    authDomain: 'oragnizamais.firebaseapp.com',
    storageBucket: 'oragnizamais.firebasestorage.app',
    measurementId: 'G-X1TW2SG94F',
  );
}
